spring.application.name=nova


jwt.secret=your-256-bit-secret-key-here-make-it-at-least-32-bytes-long

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# Brevo SMTP Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=977752001@smtp-brevo.com
spring.mail.password=ZtYv17Eg5zOyKUka
spring.mail.protocol=smtp

# SMTP Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# Debug (remove in production)
spring.mail.properties.mail.debug=false

# Mail Configuration (Gmail example)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=hilaryemujede48@gmail.com
#spring.mail.password=lbosvslmuurbvvzv
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
#spring.mail.properties.mail.smtp.connection-timeout=10000
#spring.mail.properties.mail.smtp.timeout=10000
#spring.mail.properties.mail.smtp.write-timeout=10000

# App Configuration
app.name=Nova
app.mail.from=hilaryemujede48@gmail.com


