spring.application.name=nova

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Redis Configuration
spring.data.redis.ssl.enabled=true
spring.data.redis.timeout=10000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

# Brevo SMTP Configuration
brevo.api.key=${BREVO_API_KEY}
app.mail.from=${MAIL_FROM}

#Health
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

server.port=${PORT:8080}

# App Configuration
app.name=Nova



